version: '3.7'

services:

  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - mongo
  app:
    restart: always
    build: ./nginx
    working_dir: /app
    volumes:
      - ../../doodle-assignment:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean install spring-boot:run
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: hal9000
      MONGO_INITDB_ROOT_PASSWORD: imafraidicantdothat
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo
    links:
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hal9000
      ME_CONFIG_MONGODB_ADMINPASSWORD: imafraidicantdothat
